Outputs used in the paper

In [8]:
import chess
from preprocess import *
import torch

In [3]:
board = chess.Board() 
print(board)

r n b q k b n r
p p p p p p p p
. . . . . . . .
. . . . . . . .
. . . . . . . .
. . . . . . . .
P P P P P P P P
R N B Q K B N R


In [4]:
piece_to_val = {}
val = 1
num_board = board
for square in chess.SQUARES:
    piece = board.piece_at(square)
    if piece is not None:
        print(f"Square {chess.square_name(square)} has piece {piece}")
        if piece in piece_to_val:
            
        else:
            
    else:
        print(f"Square {chess.square_name(square)} is empty")

Square a1 has piece R
Square b1 has piece N
Square c1 has piece B
Square d1 has piece Q
Square e1 has piece K
Square f1 has piece B
Square g1 has piece N
Square h1 has piece R
Square a2 has piece P
Square b2 has piece P
Square c2 has piece P
Square d2 has piece P
Square e2 has piece P
Square f2 has piece P
Square g2 has piece P
Square h2 has piece P
Square a3 is empty
Square b3 is empty
Square c3 is empty
Square d3 is empty
Square e3 is empty
Square f3 is empty
Square g3 is empty
Square h3 is empty
Square a4 is empty
Square b4 is empty
Square c4 is empty
Square d4 is empty
Square e4 is empty
Square f4 is empty
Square g4 is empty
Square h4 is empty
Square a5 is empty
Square b5 is empty
Square c5 is empty
Square d5 is empty
Square e5 is empty
Square f5 is empty
Square g5 is empty
Square h5 is empty
Square a6 is empty
Square b6 is empty
Square c6 is empty
Square d6 is empty
Square e6 is empty
Square f6 is empty
Square g6 is empty
Square h6 is empty
Square a7 has piece p
Square b7 has piec

In [19]:
import chess

def convert_board_to_numbers(board):
    # Define a mapping of chess piece constants to unique numbers
    piece_to_number = {
        chess.PAWN: 1,
        chess.KNIGHT: 2,
        chess.BISHOP: 3,
        chess.ROOK: 4,
        chess.QUEEN: 5,
        chess.KING: 6,
    }
    
    # Initialize an empty 2D list to represent the converted board
    converted_board = [[0] * 8 for _ in range(8)]
    
    # Iterate through the squares and populate the converted board
    for square in chess.SQUARES:
        piece = board.piece_at(square)
        if piece is not None:
            # Determine the color and piece type to get the unique number
            piece_number = piece_to_number[piece.piece_type] + (piece.color == chess.BLACK) * 6
            converted_board[chess.square_rank(square)][chess.square_file(square)] = piece_number
    
    return converted_board

# Example usage:
board = chess.Board()
board.push_san("e4")
board.push_san("e5")
board.push_san("Qh5")
board.push_san("Nc6")
converted = convert_board_to_numbers(board)
for row in converted:
    print(row)


[4, 2, 3, 0, 6, 3, 2, 4]
[1, 1, 1, 1, 0, 1, 1, 1]
[0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 1, 0, 0, 0]
[0, 0, 0, 0, 7, 0, 0, 5]
[0, 0, 8, 0, 0, 0, 0, 0]
[7, 7, 7, 7, 0, 7, 7, 7]
[10, 0, 9, 11, 12, 9, 8, 10]


In [6]:
print(type(converted))

<class 'list'>


In [20]:
conv_board_tensor = torch.tensor(converted)
conv_board_tensor = torch.flip(conv_board_tensor, [0])
conv_board_tensor = conv_board_tensor.unsqueeze(0)
conv_board_tensor

tensor([[[10,  0,  9, 11, 12,  9,  8, 10],
         [ 7,  7,  7,  7,  0,  7,  7,  7],
         [ 0,  0,  8,  0,  0,  0,  0,  0],
         [ 0,  0,  0,  0,  7,  0,  0,  5],
         [ 0,  0,  0,  0,  1,  0,  0,  0],
         [ 0,  0,  0,  0,  0,  0,  0,  0],
         [ 1,  1,  1,  1,  0,  1,  1,  1],
         [ 4,  2,  3,  0,  6,  3,  2,  4]]])

In [21]:
print(board)

r . b q k b n r
p p p p . p p p
. . n . . . . .
. . . . p . . Q
. . . . P . . .
. . . . . . . .
P P P P . P P P
R N B . K B N R


In [22]:
board_rep = board_to_rep(board)

In [27]:
torch.tensor(board_rep)

tensor([[[ 0,  0,  0,  0,  0,  0,  0,  0],
         [-1, -1, -1, -1,  0, -1, -1, -1],
         [ 0,  0,  0,  0,  0,  0,  0,  0],
         [ 0,  0,  0,  0, -1,  0,  0,  0],
         [ 0,  0,  0,  0,  1,  0,  0,  0],
         [ 0,  0,  0,  0,  0,  0,  0,  0],
         [ 1,  1,  1,  1,  0,  1,  1,  1],
         [ 0,  0,  0,  0,  0,  0,  0,  0]],

        [[-1,  0,  0,  0,  0,  0,  0, -1],
         [ 0,  0,  0,  0,  0,  0,  0,  0],
         [ 0,  0,  0,  0,  0,  0,  0,  0],
         [ 0,  0,  0,  0,  0,  0,  0,  0],
         [ 0,  0,  0,  0,  0,  0,  0,  0],
         [ 0,  0,  0,  0,  0,  0,  0,  0],
         [ 0,  0,  0,  0,  0,  0,  0,  0],
         [ 1,  0,  0,  0,  0,  0,  0,  1]],

        [[ 0,  0,  0,  0,  0,  0, -1,  0],
         [ 0,  0,  0,  0,  0,  0,  0,  0],
         [ 0,  0, -1,  0,  0,  0,  0,  0],
         [ 0,  0,  0,  0,  0,  0,  0,  0],
         [ 0,  0,  0,  0,  0,  0,  0,  0],
         [ 0,  0,  0,  0,  0,  0,  0,  0],
         [ 0,  0,  0,  0,  0,  0,  0,  0],
       

In [31]:
print(board)
move = move_to_rep("Bc4", board)
move


r . b q k b n r
p p p p . p p p
. . n . . . . .
. . . . p . . Q
. . . . P . . .
. . . . . . . .
P P P P . P P P
R N B . K B N R


array([[[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]]])